#FROM alpine:3.12.0 AS wrapper_s1
FROM nickgryg/alpine-pandas
RUN apk add --no-cache python3 py3-pip
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN apk update
RUN apk add make automake gcc g++ subversion python3-dev git libffi-dev
RUN python3 -m pip install --upgrade pip --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org oauthlib -vvv
RUN pip install wheel --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org oauthlib -vvv

COPY requirements_main.txt .
#RUN pip install pandas --no-cache-dir --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org oauthlib -vvv

#FROM merit/tracwrapper:s1 AS wrapper_s2
#COPY --from=wrapper_s1 /opt/venv/ /opt/venv/
RUN pip install pypandoc --no-cache-dir --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org oauthlib -vvv
RUN pip install pyspark --no-cache-dir --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org oauthlib -vvv
RUN pip install -r requirements_main.txt --no-cache-dir --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org oauthlib -vvv

RUN apk add build-base cmake bash autoconf zlib-dev flex bison

RUN pip install --extra-index-url https://pypi.fury.io/arrow-nightlies/pyarrow-1.1.0.dev11-cp36-cp36m-manylinux2014_x86_64.whl \
        --prefer-binary --no-cache-dir pandas --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host pypi.fury.io oauthlib -vvv

COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org oauthlib -vvv
WORKDIR /app

# install the dependencies and packages in the requirements file
# RUN pip install -r requirements.txt

# copy every content from the local file to the image
COPY . /app

# configure the container to run in an executed manner
ENTRYPOINT [ "python" ]

CMD ["view.py" ]